SELECT LOC.NOME FROM LOCATARIO AS LOC
    WHERE LOC.DATA_NASCIMENTO < (
        SELECT MAX(ANF.DATA_NASCIMENTO) FROM ANFITRIAO ANF
    );

SELECT LOC.NOME FROM LOCATARIO AS LOC
    WHERE LOC.DATA_NASCIMENTO < (
        SELECT MIN(ANF.DATA_NASCIMENTO) FROM ANFITRIAO ANF
    );