DROP TABLE IF EXISTS ANFITRIAO CASCADE;
CREATE TABLE IF NOT EXISTS ANFITRIAO (
    NOME            VARCHAR(250)    ,
    TELEFONE        DECIMAL(11)     ,
    ENDERECO        VARCHAR(250)    NOT NULL, -- rua número / cidade / estado
    SEXO            CHAR(1)         NOT NULL,
    DATA_NASCIMENTO DATE            NOT NULL,
    EMAIL           VARCHAR(50)     NOT NULL,
    SENHA           VARCHAR(50)     NOT NULL,
    CONTA_BANCARIA  VARCHAR(10)     NOT NULL,
    NUM_ROTEAMENTO  DECIMAL(9)      NOT NULL,
    TIPO_CONTA      DECIMAL(1)      NOT NULL,
    
    CONSTRAINT PK_ANFITRIAO PRIMARY KEY(NOME, TELEFONE),
    
    CONSTRAINT CHECK_SENHA_LEN CHECK (LENGTH(SENHA) >= 8),
    CONSTRAINT ENDERECO_ANF_UNIQUE UNIQUE(ENDERECO)
);

DROP TABLE IF EXISTS LOCATARIO CASCADE;
CREATE TABLE IF NOT EXISTS LOCATARIO(
    NOME            VARCHAR(250)    ,
    TELEFONE        DECIMAL(11)     ,
    ENDERECO        VARCHAR(250)    NOT NULL,
    SEXO            CHAR(1)         NOT NULL,
    DATA_NASCIMENTO DATE            NOT NULL,
    EMAIL           VARCHAR(50)     NOT NULL,
    SENHA           VARCHAR(50)     NOT NULL,

    CONSTRAINT PK_LOCATARIO PRIMARY KEY(NOME, TELEFONE),
    
    CONSTRAINT CHECK_SENHA_LEN CHECK (LENGTH(SENHA) >= 8),
    CONSTRAINT ENDERECO_LOC_UNIQUE UNIQUE(ENDERECO)
);

DROP TABLE IF EXISTS PROPRIEDADE CASCADE;
CREATE TABLE IF NOT EXISTS PROPRIEDADE (
    NOME            VARCHAR(250),
    ENDERECO        VARCHAR(250),
    NOME_ANF        VARCHAR(250),
    TELEFONE_ANF    DECIMAL(11),
    COMPARTILHADO   BOOLEAN     NOT NULL,
    PRECO_NOITE     FLOAT       NOT NULL,
    N_BANHEIROS     INT         NOT NULL,
    N_QUARTOS       INT         NOT NULL,
    MAX_HOSP        INTEGER     NOT NULL,
    MIN_NOITES      INTEGER     NOT NULL,
    MAX_NOITES      INTEGER     NOT NULL,
    TAXA_LIMPEZA    FLOAT,
    CHECK_IN        TIME        NOT NULL,
    CHECK_OUT       TIME        NOT NULL,

    CONSTRAINT PK_ENDERECO PRIMARY KEY(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF),

    CONSTRAINT FK_ANF FOREIGN KEY (NOME_ANF, TELEFONE_ANF) REFERENCES ANFITRIAO(NOME, TELEFONE) ON DELETE CASCADE,

    CONSTRAINT preco_noite_positivo CHECK (PRECO_NOITE > 0),
    CONSTRAINT taxa_limpeza_positivo CHECK (TAXA_LIMPEZA > 0),
    CONSTRAINT banheiros_positivo CHECK (N_BANHEIROS > 0)
);

DROP TABLE IF EXISTS QUARTO CASCADE;
CREATE TABLE IF NOT EXISTS QUARTO (
    COD_QUARTO      INTEGER,
    NOME_PROP       VARCHAR(250),
    ENDERECO_PROP   VARCHAR(250),
    N_CAMAS         INTEGER,

    CONSTRAINT PK_QUARTO PRIMARY KEY(COD_QUARTO, NOME_PROP, ENDERECO_PROP),
    
    CONSTRAINT n_camas_positivo CHECK (N_CAMAS > 0)
);

DROP TABLE IF EXISTS CAMA CASCADE;
CREATE TABLE IF NOT EXISTS CAMA (
    COD_CAMA        INTEGER,
    COD_QUARTO      INTEGER,
    NOME_PROP       VARCHAR(250),
    ENDERECO_PROP   VARCHAR(250),
    TIPO            VARCHAR(250),

    CONSTRAINT PK_CAMA PRIMARY KEY(COD_CAMA, COD_QUARTO, NOME_PROP, ENDERECO_PROP)
);

DROP TABLE IF EXISTS REGRA CASCADE;
CREATE TABLE IF NOT EXISTS REGRA (
    REGRA           VARCHAR(250)    PRIMARY KEY
);

DROP TABLE IF EXISTS PROPRIEDADE_POSSUI_REGRA CASCADE;
CREATE TABLE IF NOT EXISTS PROPRIEDADE_POSSUI_REGRA (
    REGRA           VARCHAR(250),
    NOME_PROP       VARCHAR(250),
    ENDERECO_PROP   VARCHAR(250),
    NOME_ANF        VARCHAR(250),
    TELEFONE_ANF    DECIMAL(11),
    VALOR_REGRA     BOOLEAN,

    CONSTRAINT PK_PROPRIEDADE_POSSUI_REGRA PRIMARY KEY(REGRA, NOME_PROP, ENDERECO_PROP),

    CONSTRAINT FK_PROPRIEDADE FOREIGN KEY(NOME_PROP, ENDERECO_PROP, NOME_ANF, TELEFONE_ANF) REFERENCES PROPRIEDADE(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF) ON DELETE CASCADE
);

DROP TABLE IF EXISTS COMODIDADE CASCADE;
CREATE TABLE IF NOT EXISTS COMODIDADE (
    COMODIDADE      VARCHAR(250)    PRIMARY KEY
);

DROP TABLE IF EXISTS PROPRIEDADE_POSSUI_COMODIDADE CASCADE;
CREATE TABLE IF NOT EXISTS PROPRIEDADE_POSSUI_COMODIDADE (
    COMODIDADE      VARCHAR(100),
    ENDERECO_PROP   VARCHAR(250),
    NOME_PROP       VARCHAR(250),
    NOME_ANF        VARCHAR(250),
    TELEFONE_ANF    DECIMAL(11),
    VALOR           BOOLEAN,
    
    CONSTRAINT PK_PROPRIEDADE_POSSUI_COMODIDADE PRIMARY KEY (COMODIDADE, ENDERECO_PROP, NOME_PROP),
    
    CONSTRAINT FK_PROPRIEDADE FOREIGN KEY(NOME_PROP, ENDERECO_PROP, NOME_ANF, TELEFONE_ANF) REFERENCES PROPRIEDADE(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF) ON DELETE CASCADE
);

DROP TABLE IF EXISTS DISPONIBILIDADE CASCADE;
CREATE TABLE IF NOT EXISTS DISPONIBILIDADE (
    DATA_INI        DATE,
    DATA_FIM        DATE,
    NOME_PROP       VARCHAR(250),
    ENDERECO_PROP   VARCHAR(250),
    NOME_ANF        VARCHAR(250),
    TELEFONE_ANF    DECIMAL(11),
    
    
    CONSTRAINT PK_DISPONIBILIDADE PRIMARY KEY(DATA_INI, DATA_FIM, ENDERECO_PROP, NOME_PROP),

    CONSTRAINT FK_PROPRIEDADE FOREIGN KEY(NOME_PROP, ENDERECO_PROP, NOME_ANF, TELEFONE_ANF) REFERENCES PROPRIEDADE(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF) ON DELETE CASCADE,
    
    CONSTRAINT DATES CHECK (DATA_FIM > DATA_INI)
);

DROP TABLE IF EXISTS ESTADIA CASCADE;
CREATE TABLE IF NOT EXISTS ESTADIA (
   DATA_CHECKIN     DATE,
   NOME_ANF         VARCHAR(250),
   TELEFONE_ANF     DECIMAL(11),
   NOME_PROP        VARCHAR(250),
   ENDERECO_PROP    VARCHAR(250),
   NOME_LOC         VARCHAR(250),
   TELEFONE_LOC     DECIMAL(11),
   DATA_CHECKOUT    DATE            NOT NULL,
   DATA_RESERVA     TIMESTAMP       NOT NULL,
   NUM_HOSPEDES     DECIMAL(2)      NOT NULL,
   PRECO_TOTAL      FLOAT,
   IMPOSTO          FLOAT,
   PRECO_TAXA       FLOAT,
   CODIGO_PROMO     VARCHAR(20),
   VALOR_DESCONTO   FLOAT,
   DATA_CONFIRMA    DATE,
   
   CONSTRAINT PK_ESTADIA PRIMARY KEY(DATA_CHECKIN, NOME_PROP, ENDERECO_PROP, NOME_LOC, TELEFONE_LOC),
   
   CONSTRAINT FK_PROPRIEDADE FOREIGN KEY(NOME_PROP, ENDERECO_PROP, NOME_ANF, TELEFONE_ANF) REFERENCES PROPRIEDADE(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF) ON DELETE CASCADE,
   CONSTRAINT FK_LOC FOREIGN KEY(NOME_LOC, TELEFONE_LOC) REFERENCES LOCATARIO(NOME, TELEFONE) ON DELETE CASCADE,

   CONSTRAINT DATA_CONFIRMA_ANTES_CHECKIN CHECK (DATA_CHECKIN > DATA_CONFIRMA),
   CONSTRAINT NUM_HOSPEDES_POSITIVO CHECK (NUM_HOSPEDES > 0),
   CONSTRAINT PRECO_TOTAL_POSITIVO  CHECK (PRECO_TOTAL >= 0),
   CONSTRAINT IMPOSTO_POSITIVO CHECK (IMPOSTO >= 0),
   CONSTRAINT PRECO_TAXA_POSITIVO CHECK (PRECO_TAXA >= 0),
   CONSTRAINT VALOR_DESCONTO_POSITIVO CHECK (VALOR_DESCONTO >= 0)
);

DROP TABLE IF EXISTS AVALIACAO CASCADE;
CREATE TABLE IF NOT EXISTS AVALIACAO (
    TIME_STAMP      TIMESTAMP,
    NOME_LOC        VARCHAR(250),
    TELEFONE_LOC    DECIMAL(11),  
    NOME_ANF        VARCHAR(250),
    TELEFONE_ANF    DECIMAL(11),
    NOME_PROP       VARCHAR(250),
    ENDERECO_PROP   VARCHAR(250),
    FOTOS           BYTEA,
    NOTA_PRECO      DECIMAL(1),
    NOTA_LIMPEZA    DECIMAL(1),
    NOTA_COMUN      DECIMAL(1),  -- NOTA COMUNICACAO
    NOTA_LOC        DECIMAL(1),
    TEXTO           VARCHAR(500) NOT NULL,

    CONSTRAINT PK_AVALIACAO PRIMARY KEY(TIME_STAMP, NOME_LOC, TELEFONE_LOC, NOME_ANF, TELEFONE_ANF, NOME_PROP, ENDERECO_PROP),

    CONSTRAINT FK_PROPRIEDADE FOREIGN KEY(NOME_PROP, ENDERECO_PROP, NOME_ANF, TELEFONE_ANF) REFERENCES PROPRIEDADE(NOME, ENDERECO, NOME_ANF, TELEFONE_ANF) ON DELETE CASCADE,
    CONSTRAINT FK_LOC FOREIGN KEY(NOME_LOC, TELEFONE_LOC) REFERENCES LOCATARIO(NOME, TELEFONE) ON DELETE CASCADE,

    CONSTRAINT NOTA_PRECO CHECK ((NOTA_PRECO >= 0) AND (NOTA_PRECO <= 5)),
    CONSTRAINT NOTA_LIMPEZA CHECK ((NOTA_LIMPEZA >= 0) AND (NOTA_LIMPEZA <= 5)),
    CONSTRAINT NOTA_COMUN CHECK ((NOTA_COMUN >= 0) AND (NOTA_COMUN <= 5)),
    CONSTRAINT NOTA_LOC CHECK ((NOTA_LOC >= 0) AND (NOTA_LOC <= 5))
);