CREATE TABLE IF NOT EXISTS ANFITRIAO {
    NOME            VARCHAR(250)    ,
    TELEFONE        INTEGER(11)     ,
    ENDERECO        VARCHAR(250)    NOT NULL, -- rua número / cidade / estado
    SEXO            CHAR(1)         NOT NULL,
    DATA_NASCIMENTO DATE            NOT NULL,
    EMAIL           VARCHAR(50)     NOT NULL,
    SENHA           VARCHAR(50)     NOT NULL,
    CONTA_BANCARIA  VARCHAR(10)     NOT NULL,
    NUM_ROTEAMENTO  INTEGER(9)      NOT NULL,
    TIPO_CONTA      INTEGER(1)      NOT NULL,
    
    ADD CONSTRAINT PK_ANFITRIAO PRIMARY KEY(NOME, TELEFONE),
    
    ADD CONSTRAINT CHECK_SENHA_LEN CHECK (LEN(SENHA) >= 8),
    ADD CONSTRAINT ENDERECO_UNIQUE UNIQUE(ENDERECO)
};

CREATE TABLE IF NOT EXISTS LOCATARIO{
    NOME            VARCHAR(250)    ,
    TELEFONE        INTEGER(11)     ,
    ENDERECO        VARCHAR(250)    NOT NULL,
    SEXO            CHAR(1)         NOT NULL,
    DATA_NASCIMENTO DATE            NOT NULL,
    EMAIL           VARCHAR(50)     NOT NULL,
    SENHA           VARCHAR(50)     NOT NULL,

    ADD CONSTRAINT PK_LOCATARIO PRIMARY KEY(NOME, TELEFONE),
    
    ADD CONSTRAINT CHECK_SENHA_LEN CHECK (LEN(SENHA) >= 8),
    ADD CONSTRAINT ENDERECO_UNIQUE UNIQUE(ENDERECO)
};

CREATE TABLE IF NOT EXISTS PROPRIEDADE {
    nome            VARCHAR(250),
    endereco        VARCHAR(250),
    nome_anf        VARCHAR(250),
    telefone_anf    VARCHAR(250),
    compartilhado   BOOLEAN     NOT NULL,
    preco_noite     FLOAT       NOT NULL,
    n_banheiros     INT         NOT NULL,
    n_quartos       INT         NOT NULL,
    max_hosp        INTEGER     NOT NULL,
    min_noites      INTEGER     NOT NULL,
    max_noites      INTEGER     NOT NULL,
    taxa_limpeza    FLOAT,
    check_in        TIME        NOT NULL,
    check_out       TIME        NOT NULL,

    ADD CONSTRAINT PK_ENDERECO PRIMARY KEY(nome, endereco, nome_anf, telefone_anf),

    ADD CONSTRAINT FK_NOME FOREIGN KEY (NOME_ANF) REFERENCES ANFITRIAO(NOME),
    ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (ENDERECO_ANF) REFERENCES ANFITRIAO(ENDERECO),
    
    ADD CONSTRAINT preco_noite_positivo CHECK (preco_noite > 0),
    ADD CONSTRAINT taxa_limpeza_positivo CHECK (taxa_limpeza > 0),
    ADD CONSTRAINT banheiros_positivo CHECK (n_banheiros > 0),
};

CREATE TABLE IF NOT EXISTS QUARTO {
    cod_quarto      INTEGER,
    nome_p          VARCHAR(250),
    endereco_p      VARCHAR(250),
    n_camas         INTEGER,

    ADD CONSTRAINT PK_QUARTO PRIMARY KEY(cod_quarto, nome_p, endereco_p)
    
    ADD CONSTRAINT n_camas_positivo CHECK (n_camas > 0),
};

CREATE TABLE IF NOT EXISTS CAMA {
    cod_cama        INTEGER,
    cod_quarto      INTEGER,
    nome_p          VARCHAR(250),
    endereco_p      VARCHAR(250),
    tipo            VARCHAR(250),

    ADD CONSTRAINT PK_CAMA PRIMARY KEY(cod_cama, cod_quarto, nome_p, endereco_p)
}

CREATE TABLE IF NOT EXISTS REGRA {
    regra           VARCHAR(250)    PRIMARY KEY
};

CREATE TABLE IF NOT EXISTS PROPRIEDADE_POSSUI_REGRA {
    regra           VARCHAR(250),
    nome_prop       VARCHAR(250),
    end_prop        VARCHAR(250),
    valor_regra     BOOLEAN

    ADD CONSTRAINT PK_PROPRIEDADE_POSSUI_REGRA PRIMARY KEY(regra, nome_prop, end_prop),
};

CREATE TABLE IF NOT EXISTS COMODIDADE {
    comodidade      VARCHAR(250)    PRIMARY KEY,
};

CREATE TABLE IF NOT EXISTS PROPRIEDADE_POSSUI_COMODIDADE {
    COMODIDADE      VARCHAR(100),
    ENDERECO_PROP   VARCHAR(250),
    NOME_PROP       VARCHAR(250),
    VALOR           BOOLEAN,
    
    ADD CONSTRAINT PK_PROPRIEDADE_POSSUI_COMODIDADE PRIMARY KEY (COMODIDADE, ENDERECO_PROP, NOME_PROP),
    
    ADD CONSTRAINT FK_ENDERECO_PROP FOREIGN KEY(ENDERECO_PROP) REFERENCES PROPRIEDADE(ENDERECO),
    ADD CONSTRAINT FK_NOME_PROP FOREIGN KEY(NOME_PROP) REFERENCES PROPRIEDADE(NOME)
};

CREATE TABLE IF NOT EXISTS DISPONIBILIDADE {
    DATA_INI        DATE,
    DATA_FIM        DATE,
    NOME_P          VARCHAR(250),
    ENDERECO_P      VARCHAR(250),
    
    ADD CONSTRAINT PK_DISPONIBILIDADE PRIMARY KEY(DATA_INI, DATA_FIM, ENDERECO_P, NOME_P),

    ADD CONSTRAINT FK_NOME_PROP FOREIGN KEY(NOME_PROP) REFERENCES PROPRIEDADE(NOME)
    ADD CONSTRAINT FK_ENDERECO_PROP FOREIGN KEY(ENDERECO_PROP) REFERENCES PROPRIEDADE(ENDERECO),
    
    ADD CONSTRAINT DATES CHECK DATA_FIM > DATA_INI
};

CREATE TABLE IF NOT EXISTS ESTADIA {
   DATA_CHECKIN     DATE,
   NOME_PROP        VARCHAR(250),
   ENDERECO_PROP    VARCHAR(250),
   NOME_LOC         VARCHAR(250),
   TELEFONE_LOC     VARCHAR(250),
   DATA_CHECKOUT    DATE            NOT NULL,
   DATA_RESERVA     TIMESTAMP       NOT NULL,
   NUM_HOSPEDES     INTEGER(2)      NOT NULL,
   PRECO_TOTAL      FLOAT,
   IMPOSTO          FLOAT,
   PRECO_TAXA       FLOAT,
   CODIGO_PROMO     VARCHAR(10),
   VALOR_DESCONTO   FLOAT,
   DATA_CONFIRMA    TIMESTAMP,
   

   ADD CONSTRAINT PK_ESTADIA PRIMARY KEY(DATA_CHECKIN, NOME_PROP, ENDERECO_PROP, NOME_LOC, TELEFONE_LOC),

   ADD CONSTRAINT FOREIGN KEY(NOME_LOC) REFERENCES LOCATARIO(NOME),
   ADD CONSTRAINT FOREIGN KEY(TELEFONE_LOC) REFERENCES LOCATARIO(TELEFONE),
   ADD CONSTRAINT FOREIGN KEY(NOME_PROP) REFERENCES PROPRIEDADE(NOME),
   ADD CONSTRAINT FOREIGN KEY(ENDERECO_PROP) REFERENCES PROPRIEDADE(ENDERECO),
   
   ADD CONSTRAINT DATA_CONFIRMA_ANTES_CHECKIN CHECK (DATA_CHECKIN > DATA_CONFIRMA),
   ADD CONSTRAINT NUM_HOSPEDES_POSITIVO CHECK (NUM_HOSPEDES > 0),
   ADD CONSTRAINT PRECO_TOTAL_POSITIVO  CHECK (PRECO_TOTAL >= 0),
   ADD CONSTRAINT IMPOSTO_POSITIVO CHECK (IMPOSTO >= 0),
   ADD CONSTRAINT PRECO_TAXA_POSITIVO CHECK (PRECO_TAXA >= 0),
   ADD CONSTRAINT VALOR_DESCONTO_POSITIVO CHECK (VALOR_DESCONTO >= 0),
};

CREATE TABLE IF NOT EXISTS AVALIACAO {
    TIME_STAMP      TIMESTAMP,   
    NOME_LOC        VARCHAR(250),   
    TELEFONE_LOC    VARCHAR(250),  
    NOME_ANF        VARCHAR(250),   
    TELEFONE_ANF    INTEGER(11),   
    NOME_PROP       VARCHAR(250),
    END_PROP        VARCHAR(250),
    FOTOS           BLOB,
    NOTA_PRECO      INTEGER(1),
    NOTA_LIMPEZA    INTEGER(1),
    NOTA_COMUN      INTEGER(1),     -- NOTA COMUNICACAO
    NOTA_LOC        INTEGER(1),
    TEXTO           VARCHAR(500)    NOT NULL,


    ADD CONSTRAINT PK_AVALIACAO PRIMARY KEY(TIME_STAMP, NOME_LOC, TELEFONE_LOC, NOME_ANF, TELEFONE_ANF, NOME_PROP, END_PROP),

    ADD CONSTRAINT FOREIGN KEY(NOME_LOC) REFERENCES LOCATARIO(NOME),
    ADD CONSTRAINT FOREIGN KEY(TELEFONE_LOC) REFERENCES LOCATARIO(TELEFONE),
    ADD CONSTRAINT FOREIGN KEY(NOME_ANF) REFERENCES ANFITRIAO(NOME),
    ADD CONSTRAINT FOREIGN KEY(TELEFONE_ANF) REFERENCES ANFITRIAO(TELEFONE),
    ADD CONSTRAINT FOREIGN KEY(NOME_PROP) REFERENCES PROPRIEDADE(NOME),
    ADD CONSTRAINT FOREIGN KEY(END_PROP) REFERENCES PROPRIEDADE(ENDERECO),

    ADD CONSTRAINT NOTA_PRECO CHECK (NOTA_PRECO >= 0) AND (NOTA_PRECO <= 5),
    ADD CONSTRAINT NOTA_LIMPEZA CHECK (NOTA_LIMPEZA >= 0) AND (NOTA_LIMPEZA <= 5), 
    ADD CONSTRAINT NOTA_COMUN CHECK (NOTA_COMUN >= 0) AND (NOTA_COMUN <= 5),
    ADD CONSTRAINT NOTA_LOC CHECK (NOTA_LOC >= 0) AND (NOTA_LOC <= 5),
};
