SELECT DATA_CHECKIN, NOME_PROP, ENDERECO_PROP, NOME_LOC, TELEFONE_LOC
  FROM ESTADIA
  WHERE 
    (DATA_CONFIRMA IS NOT NULL) AND (DATA_CHECKIN > '2024-04-01');

SELECT
  DATA_CHECKIN, 
  NOME_PROP, 
  (DATA_CHECKOUT - DATA_CHECKIN) AS DIAS_LOCADOS
    FROM ESTADIA
    WHERE 
      (DATA_CONFIRMA IS NOT NULL) AND (DATA_CHECKIN > '2024-04-01') AND (DATA_CHECKOUT IS NOT NULL);
      
SELECT
  DATA_CHECKIN,
  NOME_PROP,
  NOME_LOC,
  NOME_ANF
  FROM ESTADIA
    WHERE 
      (DATA_CONFIRMA IS NOT NULL) AND (DATA_CHECKIN > '2024-04-01') AND (DATA_CHECKOUT IS NOT NULL);

SELECT
  E.DATA_CHECKIN,
  E.NOME_PROP,
  P.preco_noite
  FROM ESTADIA E
  JOIN PROPRIEDADE P ON (E.NOME_PROP = P.NOME) AND (E.ENDERECO_PROP = P.ENDERECO)
    WHERE 
      (E.DATA_CONFIRMA IS NOT NULL) AND (E.DATA_CHECKIN > '2024-04-01') AND (E.DATA_CHECKOUT IS NOT NULL);
