SELECT EXTRACT(MONTH FROM DATA_CHECKIN) AS mes,
	AVG(PRECO_TOTAL / (DATA_CHECKOUT - DATA_CHECKIN)) AS valor_medio_diarias_feitas,
	AVG(CASE WHEN DATA_CONFIRMA IS NOT NULL THEN PRECO_TOTAL / (DATA_CHECKOUT - DATA_CHECKIN) END) AS valor_medio_diarias_confirmadas
	FROM
		ESTADIA
	GROUP BY
		mes